### ISSUE TITLE
Support for PIC24F family?

### ISSUE THREAD

**Issue by roman959** [pololu/rpicsim#2]
Hello,

I am very interested in using RPicSim for a new project involving a PIC24FV32KA302 device.  However, right off the bat, I ran into the following error:
```
  ArgumentError:
     Cannot find SFR or NMMR named '...'
```
for both WREG and STKPTR registers.  And sure enough, these registers appear to be unavailable in MPLAB X Simulator (i.e., I cannot set a watch for these registers).  I have tried MPLAB X IDE versions 2.20 and 2.35.  Compiler is XC16 v1.24.

Has anyone run into this issue before, and if so, is there a workaround?

Many thanks,

-Roman

**Comment by DavidEGrayson** [comment]
Hello.  RPicSim only [supports](http://pololu.github.io/rpicsim/file.SupportedDevices.html) the 8-bit PICs right now because those are the ones we are most interested in.  If you want to get it working for your device, you could probably try just commenting out the lines that are giving you trouble, but that might cause other problems in later parts of the code.  For example, I know that the `run_subroutine` command uses a class that ultimately access the `STKPTR` register.  If your device doesn't have a `STKPTR` register, then `run_subroutine` would need to be modified if you want it to work.
